### ISSUE TITLE
Broken API '/api/profile' after login with password

### ISSUE THREAD

**Issue by simon-ebner** [webauthn4j/webauthn4j-spring-security#1317]
How to produce?

* Checkout commit **2b063c16** and create new user account with password and then login via password authentication.
The user profile API resource '/api/profile' fails with the following error.

`2023-10-16T19:27:14.681+02:00 ERROR 88233 --- [nio-8080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.orm.jpa.JpaSystemException: Error attempting to apply AttributeConverter] with root cause

java.lang.IllegalArgumentException: argument "src" is null
        at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4885)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3737)
        at com.webauthn4j.converter.util.CborConverter.readValue(CborConverter.java:55)
        at com.webauthn4j.springframework.security.webauthn.sample.infrastructure.util.jpa.converter.COSEKeyConverter.convertToEntityAttribute(COSEKeyConverter.java:43)
        at com.webauthn4j.springframework.security.webauthn.sample.infrastructure.util.jpa.converter.COSEKeyConverter.convertToEntityAttribute(COSEKeyConverter.java:26)
        at org.hibernate.metamodel.model.convert.internal.JpaAttributeConverterImpl.toDomainValue(JpaAttributeConverterImpl.java:86)
        at org.hibernate.sql.results.graph.basic.BasicResultAssembler.assemble(BasicResultAssembler.java:80)
`

The Spring and Spring Security migration may be the issue here.
It could also relate to an issue with another library.

The commit **f7680f84** from March this year works fine so far.

Implications
* view profile information and updating it don't work

**Comment by simon-ebner** [comment]
I'm about to create a PR.

The key was wrong in 'AuthenticatorEntity.java'.
Before: 'coseKey'
After: 'cose_key'

**Comment by simon-ebner** [comment]
PR: https://github.com/webauthn4j/webauthn4j-spring-security/pull/1318

**Comment by ynojima** [comment]
Thank you for your pull-request! I merged your pull-request.
